server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: taskservice
          uri: lb://client1
          predicates:
            - Path=/**
        - id: service
          uri: lb://client3
          predicates:
            - Path=/**


     # discovery:
      #  locator:
       #   enabled: true
        #  lowerCaseServiceId: true
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka