server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product
          predicates:
            - Path=/product/**
        - id: buy
          uri: lb://buy
          predicates:
            - Path=/buy/**
        - id: reviews
          uri: lb://reviews
          predicates:
            - Path=/review/**


     # discovery:
      #  locator:
       #   enabled: true
        #  lowerCaseServiceId: true
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka