server:
  port: 0
spring:
  application:
    name: reviews
  cloud:
    discovery:
      enabled: true
eureka:
 # instance:
  #  hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka